In [1]:
import numpy as np

In [27]:
X = np.array([[1, 2104, 5, 1, 45],
              [1, 1416, 3, 2, 40],
              [1, 1534, 3, 2, 30],
              [1, 852, 2, 1, 36]])

In [30]:
y = np.array([[460],
              [232], 
              [315], 
              [178]])

In [31]:
y

array([[460],
       [232],
       [315],
       [178]])

In [32]:
Xt = X.T

In [48]:
Xt

array([[   1,    1,    1,    1],
       [2104, 1416, 1534,  852],
       [   5,    3,    3,    2],
       [   1,    2,    2,    1],
       [  45,   40,   30,   36]])

In [50]:
Xt.dot(X)

array([[      4,    5906,      13,       6,     151],
       [   5906, 9510932,   21074,    8856,  228012],
       [     13,   21074,      47,      19,     507],
       [      6,    8856,      19,      10,     221],
       [    151,  228012,     507,     221,    5821]])

In [51]:
np.linalg.inv(Xt.dot(X))

array([[-2.98428740e+13,  1.40195149e+11, -6.34710170e+13,
        -2.22162579e+13,  1.65430275e+12],
       [ 1.40195149e+11, -6.58605459e+08,  2.98172645e+11,
         1.04367012e+11, -7.77154442e+09],
       [-6.34710170e+13,  2.98172645e+11, -1.34992695e+14,
        -4.72504251e+13,  3.51843721e+12],
       [-2.22162579e+13,  1.04367012e+11, -4.72504251e+13,
        -1.65386925e+13,  1.23153074e+12],
       [ 1.65430275e+12, -7.77154442e+09,  3.51843721e+12,
         1.23153074e+12, -9.17042241e+10]])

In [39]:
theta_best = np.linalg.inv(Xt.dot(X)).dot(Xt).dot(y)
theta_best

array([[  50.06201172],
       [   0.67824173],
       [-121.5859375 ],
       [ -62.95556641],
       [  -7.37902832]])

In [42]:
X_pred = np.array([[1, 1534, 3, 2, 30]])

In [45]:
y_predict = X.dot(theta_best)

In [46]:
y_predict

array([[474.14108276],
       [224.6222229 ],
       [378.44503021],
       [ 56.15150452]])